version: '3.8'

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - 2003:80

  client:
    container_name: client
    env_file:
      - ./client/.env
    build: ./client
    ports: 
      - 3000:3000

  server:
    container_name: server
    env_file:
      - ./server/.env
    build: ./server
    ports: 
      - 3001:3001

  redis:
    container_name: redis
    image: redis
    restart: always
    ports: 
      - 6379:6379

