version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 2003:80

  client:
    container_name: client
    env_file:
      - ./client/.env
    build: ./client
    ports: 
      - 3000:3000

  server:
    container_name: server
    env_file:
      - ./server/.env
    build: ./server
    ports: 
      - 3001:3001
    # networks:
    #   - main

  mongoDB:
    container_name: mongoDB
    image: mongo
    restart: always
    ports:
      - 27017:80
    environment:
      MONGO_INITDB_DATABASE: logs
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    # networks:
    #   - main

  redis:
    container_name: redis
    image: redis
    restart: always
    ports: 
      - 2345:80
    # networks:
    #   - main