name: Deploy Next App
on:
  workflow_dispatch:
  push:
    branches: [main]
    # paths-ignore:
    #   - '.github/workflows/*'

  pull_request:
    branches: [main]
    # paths-ignore:
    #   - '.github/workflows/*'

jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout
        uses: actions/checkout@v3

      - name: Use setup-node
        uses: actions/setup-node@v3

      - name: npm install on server
        working-directory: ./server
        run: npm ci

      - name: build project
        working-directory: ./server
        run: npm run build

  server-test:
    needs: [server-build]
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout
        uses: actions/checkout@v3

      - name: Use setup-node
        uses: actions/setup-node@v3

      - name: npm install on server
        working-directory: ./server
        run: npm ci

      - name: build project
        working-directory: ./server
        run: npm run build

      - name: Test
        working-directory: ./server
        run: npm run test
